server:
  port: 8083

spring:
  application:
    name: reporting-service

  # Configuration WebFlux
  webflux:
    base-path: /

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}

# Configuration WebClient
webclient:
  exchange-api:
    base-url: https://api.exchangerate-api.com
    timeout: 5000

logging:
  level:
    com.banking.reporting: DEBUG
    reactor.netty: INFO
    org.springframework.web.reactive: DEBUG