server:
  port: 8083

spring:
  application:
    name: reporting-service

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}

exchange:
  api:
    url: https://api.exchangerate-api.com/v4/latest/USD