server:
  port: 8081

spring:
  application:
    name: compte-service

  datasource:
    url: jdbc:h2:mem:comptedb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    rest:
      base-path: /api
      default-page-size: 20
      max-page-size: 100

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}

logging:
  level:
    org.springframework.data.rest: DEBUG
    com.banking.compte: DEBUG